---
repos:
  - repo: local
    hooks:
      - id: go vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        types:
          - go
      - id: go test
        name: go test
        entry: go test ./...
        language: system
        pass_filenames: false
        types:
          - go
fail_fast: true
